/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/Account.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    Courts: typeof import('./src/components/Courts.vue')['default']
    CreateGame: typeof import('./src/components/CreateGame.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GuestUpsert: typeof import('./src/components/GuestUpsert.vue')['default']
    MemberUpsert: typeof import('./src/components/MemberUpsert.vue')['default']
    OnDeck: typeof import('./src/components/OnDeck.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    Playing: typeof import('./src/components/Playing.vue')['default']
    SelectMembers: typeof import('./src/components/SelectMembers.vue')['default']
    Waiting: typeof import('./src/components/Waiting.vue')['default']
  }
}
