/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Account: typeof import('./src/components/Account.vue')['default']
    Administration: typeof import('./src/components/Administration.vue')['default']
    Auth: typeof import('./src/components/Auth.vue')['default']
    Challenge: typeof import('./src/components/Challenge.vue')['default']
    Court: typeof import('./src/components/Court.vue')['default']
    CreateGame: typeof import('./src/components/CreateGame.vue')['default']
    CRUDEdit: typeof import('./src/components/administration/CRUDEdit.vue')['default']
    CRUDList: typeof import('./src/components/administration/CRUDList.vue')['default']
    FlyingAnimationOverlay: typeof import('./src/components/FlyingAnimationOverlay.vue')['default']
    Game: typeof import('./src/components/Game.vue')['default']
    GuestUpsert: typeof import('./src/components/GuestUpsert.vue')['default']
    Main: typeof import('./src/components/Main.vue')['default']
    MemberUpsert: typeof import('./src/components/MemberUpsert.vue')['default']
    OnDeck: typeof import('./src/components/OnDeck.vue')['default']
    Player: typeof import('./src/components/Player.vue')['default']
    PlayerAvatar: typeof import('./src/components/PlayerAvatar.vue')['default']
    Playing: typeof import('./src/components/Playing.vue')['default']
    QueueColumn: typeof import('./src/components/QueueColumn.vue')['default']
    SelectMembers: typeof import('./src/components/SelectMembers.vue')['default']
    Venue: typeof import('./src/components/Venue.vue')['default']
    Waiting: typeof import('./src/components/Waiting.vue')['default']
  }
}
